Project1/Models/Employee.cs
using System;
using System.Collections;
using Project1.Models;
using System.Collections.Generic;

namespace Project1.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HiredDate { get; set; }
        public List<Tasks> Task { get; set; }

        public Employee() { }
        public Employee(int id, string FirstName, string LastName, string HiredDate)
        {
            this.Id = id;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.HiredDate = HiredDate;
            this.Task = new List<Tasks>();
        }
    }
}

Project1/Models/Tasks.cs
using System;
namespace Project1.Models
{
    public class Tasks
    {
        public int EmployeeID { get; set; }
        public string TaskName { get; set; }
        public string StartTime { get; set; }
        public string DeadLine { get; set; }

        public Tasks() { }
        public Tasks(int EmployeeID, string TaskName, string StartTime, string DeadLine)
        {
            this.EmployeeID = EmployeeID;
            this.TaskName = TaskName;
            this.StartTime = StartTime;
            this.DeadLine = DeadLine;
        }
    }
}

Project1/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Project1.Models;
using Project1.Services;


namespace Project1.Controllers
{
    public class EmployeeController:Controller
    {
        private readonly IEmployeeServices _employeeService;

        public EmployeeController(IEmployeeServices employeeService)
        {
            _employeeService = employeeService;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Employee Index";
            var employee = await _employeeService.GetAll();
            return View(employee);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Title = "Add Employee";
            return View(new Employee());
        }

        [HttpPost]
        public async Task<IActionResult> Add(Employee model)
        {
            if (ModelState.IsValid)
            {
                await _employeeService.Add(model);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int employeeId)
        {
            if (ModelState.IsValid)
            {
                await _employeeService.Delete(employeeId);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(int employeeId, Employee model)
        {
            ViewBag.Title = "Update Employee";
            var employees = _employeeService.GetAllEmployees();
            var em = employees.FirstOrDefault(e => e.Id == employeeId);
            return View(em);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Employee model)
        {
            if (ModelState.IsValid)
            {
                await _employeeService.Update(model);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Project1/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Project1.Models;
using Project1.Services;

namespace Project1.TasksController
{
    public class TasksController:Controller
    {
        private readonly ITasksServices _taskService;
        private readonly IEmployeeServices _employeeService;
        public TasksController(ITasksServices taskService, IEmployeeServices employeeService)
        {
            _taskService = taskService;
            _employeeService = employeeService;
        }

        public async Task<IActionResult> Index(int employeeId)
        {
            var task = await _taskService.GetTasks(employeeId);
            ViewBag.EmployeeId = employeeId;
            return View(task);
        }

        [HttpGet]
        public IActionResult Add(int EmployeeId)
        {
            ViewBag.Title = "Add Employee";
            return View(new Tasks
            {
                EmployeeID = EmployeeId
            });
        }

        [HttpPost]
        public async Task<IActionResult> Add(Tasks model)
        {
            if (ModelState.IsValid)
            {
                await _taskService.Add(model);
            }
            return RedirectToAction(nameof(Index), new { EmployeeID = model.EmployeeID });
        }

        public async Task<IActionResult> Return()

        {
            return RedirectToAction("Index", "Employee");

        }
    }
}

Project1/Views/Employee/Add.cshtml
@using Project1.Models
@model Employee

<form asp-action="Add">
    <input type="hidden" asp-for="Id" />

    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="FirstName"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="FirstName" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="LastName"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="LastName" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="HiredDate"></label>
        </div>
        <div class="col-md-6">
            <input id="datepicker" class="form-control" asp-for="HiredDate" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

@section Scripts
{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>$(function () {
            $("#datepicker").datepicker();
        });</script>
}

Project1/Views/Employee/DisplayTemplates/Employee.cshtml
@using Microsoft.Extensions.Options
@using Project1
@model Project1.Models.Employee
<tr>
    <td>@Model.Id</td>
    <td>@Model.FirstName.</td>
    <td>@Model.LastName</td>
    <td>@Model.HiredDate</td>
    <td>
        <a asp-controller="Tasks" asp-action="Index" asp-route-employeeId="@Model.Id">
            Tasks
        </a>
    </td>
    <td>
        <a asp-controller="Employee" asp-action="Delete" asp-route-employeeId="@Model.Id">
            Delete
        </a>
    </td>
    <td>
        <a asp-controller="Employee" asp-action="Update" asp-route-employeeId="@Model.Id">
            Update
        </a>
    </td>
</tr>

Project1/Views/Employee/Update.cshtml
@using Project1.Models
@model Employee

<form asp-action="Update">
    <input type="hidden" asp-for="Id" />

    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="FirstName"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="FirstName" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="LastName"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="LastName" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="HiredDate"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" id="datepicker_hireddate" asp-for="HiredDate" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
</form>

@section Scripts
{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker_hireddate").datepicker();
        });
    s</script>
}

Project1/Views/Employee/index.cshtml
@using Project1.Models;
@model IEnumerable<Employee>

<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table table-striped" >
            <tr>
                <th>Id</th>
                <th>FirstName</th>
                <th>LastName</th>
                <th>HiredDate</th>
                <th>Tasks</th>
                <th>Action</th>
                <th>Action</th>
            </tr>
            @Html.DisplayForModel()
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4 offset-md-2">
        <a asp-action="Add" class="btn btn-primary btn-lg active">Add Employees</a>
    </div>
</div>

Project1/Views/Shared/_Layout.cshtml
@RenderSection("Scripts", required: false)
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SF Project</title>
    <environment include="Development">
        <link rel="stylesheet" href="/css/bootstrap.css" />
    </environment>
</head>
<body style="width:90%;">
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <span class="h2"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>

</body>
</html>

Project1/Views/Tasks/Add.cshtml
@using Project1.Models
@model Tasks

<form asp-action="Add">
    <input type="hidden" asp-for="EmployeeID" />
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="TaskName"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="TaskName" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="StartTime"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" id="datepicker_startime" asp-for="StartTime" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="DeadLine"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" id="datepicker_deadline" asp-for="DeadLine" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

@section Scripts
{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker_startime").datepicker();
            $("#datepicker_deadline").datepicker();
        });
    </script>
}

Project1/Views/Tasks/DisplayTemplates/Tasks.cshtml
@using Microsoft.Extensions.Options
@using Project1
@model Project1.Models.Tasks
<tr>
    <td>@Model.EmployeeID</td>
    <td>@Model.TaskName</td>
    <td>@Model.StartTime</td>
    <td>@Model.DeadLine</td>
</tr>

Project1/Views/Tasks/index.cshtml
@using Project1.Models;
@model IEnumerable<Tasks>


<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table table-striped">
            <tr>
                <th>EmployeeID</th>
                <th>TaskName</th>
                <th>StartTime</th>
                <th>DeadLine</th>
            </tr>
            @Html.DisplayForModel()
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-4 offset-md-2">
        <a asp-action="Add" asp-route-EmployeeId="@ViewBag.EmployeeId" class="btn btn-primary btn-lg active">Add Tasks</a>
        <a asp-action="Return" class="btn btn-primary btn-lg">Return to Index Page</a>
    </div>
    <div class="col-md-4 offset-md-2">
        
    </div>
</div>
<div class="row">
    
</div>